# Generated by Django 2.1.5 on 2021-02-01 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBasicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrimony_id', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFullDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20, null=True)),
                ('dateofbirth', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(upload_to='profile_pic/')),
                ('height', models.CharField(max_length=100, null=True)),
                ('age', models.CharField(max_length=100, null=True)),
                ('marital_status', models.CharField(max_length=100, null=True)),
                ('body_type', models.CharField(max_length=100, null=True)),
                ('food_type', models.CharField(max_length=100, null=True)),
                ('drink_habbit', models.CharField(max_length=100, null=True)),
                ('smoke_habbit', models.CharField(max_length=100, null=True)),
                ('weight', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('profession', models.CharField(max_length=100, null=True)),
                ('education', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('total_family_members', models.CharField(max_length=100, null=True)),
                ('father_details', models.CharField(max_length=100, null=True)),
                ('mother_details', models.CharField(max_length=100, null=True)),
                ('brother_details', models.CharField(max_length=100, null=True)),
                ('sister_details', models.CharField(max_length=100, null=True)),
                ('caste', models.CharField(max_length=100, null=True)),
                ('religion', models.CharField(max_length=100, null=True)),
                ('nakshatra', models.CharField(max_length=100, null=True)),
                ('rashi', models.CharField(max_length=100, null=True)),
                ('birthoftime', models.CharField(max_length=100, null=True)),
                ('basic_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony_app.UserBasicDetails')),
            ],
        ),
        migrations.AddField(
            model_name='saveotp',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony_app.UserBasicDetails'),
        ),
        migrations.AlterUniqueTogether(
            name='userbasicdetails',
            unique_together={('phone_number', 'matrimony_id')},
        ),
        migrations.AlterUniqueTogether(
            name='saveotp',
            unique_together={('phone_number',)},
        ),
    ]
