# Generated by Django 2.1.5 on 2021-02-28 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfulldetails',
            name='Few_Words_MySelf',
            field=models.TextField(default=datetime.datetime(2021, 2, 28, 16, 16, 31, 347042, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
