# Generated by Django 2.2.5 on 2021-03-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0003_auto_20210228_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfulldetails',
            name='post_graduation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfulldetails',
            name='super_speciality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfulldetails',
            name='under_graduation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
