# Generated by Django 2.2.5 on 2021-03-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0006_auto_20210302_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagetest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_pic/')),
            ],
        ),
    ]
