# Generated by Django 2.2.5 on 2021-03-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0008_auto_20210318_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner_preferences',
            old_name='height',
            new_name='max_height',
        ),
        migrations.AddField(
            model_name='partner_preferences',
            name='min_height',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
