# Generated by Django 2.2.5 on 2021-03-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0009_auto_20210318_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Under_graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_graduation', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('under_graduation',)},
            },
        ),
        migrations.CreateModel(
            name='Super_speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_speciality', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('super_speciality',)},
            },
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('stars',)},
            },
        ),
        migrations.CreateModel(
            name='Smoke_Hobbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke_Hobbit', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('smoke_Hobbit',)},
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('religion',)},
            },
        ),
        migrations.CreateModel(
            name='Rasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasi', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('rasi',)},
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('qualification',)},
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('profession',)},
            },
        ),
        migrations.CreateModel(
            name='Post_graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_graduation', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('post_graduation',)},
            },
        ),
        migrations.CreateModel(
            name='Physical_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_status', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('physical_status',)},
            },
        ),
        migrations.CreateModel(
            name='Mother_Tongue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_Tongue', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('mother_Tongue',)},
            },
        ),
        migrations.CreateModel(
            name='Mother_Occ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_Occ', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('mother_Occ',)},
            },
        ),
        migrations.CreateModel(
            name='Marital_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('marital_status',)},
            },
        ),
        migrations.CreateModel(
            name='Job_sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_sector', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('job_sector',)},
            },
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('height',)},
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('gender',)},
            },
        ),
        migrations.CreateModel(
            name='Food_Hobbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_Hobbit', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('food_Hobbit',)},
            },
        ),
        migrations.CreateModel(
            name='Father_Occ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_Occ', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('father_Occ',)},
            },
        ),
        migrations.CreateModel(
            name='Family_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_type', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('family_type',)},
            },
        ),
        migrations.CreateModel(
            name='Drink_Hobbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_Hobbit', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('drink_Hobbit',)},
            },
        ),
        migrations.CreateModel(
            name='Created_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('created_by',)},
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('citizen',)},
            },
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('caste',)},
            },
        ),
        migrations.CreateModel(
            name='Birth_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_place', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('birth_place',)},
            },
        ),
        migrations.CreateModel(
            name='Annual_income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_income', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('annual_income',)},
            },
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('age',)},
            },
        ),
    ]
