# Generated by Django 2.2.5 on 2021-03-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0010_age_annual_income_birth_place_caste_citizen_created_by_drink_hobbit_family_type_father_occ_food_hobb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfulldetails',
            old_name='drink_habbit',
            new_name='diet_preference',
        ),
        migrations.RenameField(
            model_name='userfulldetails',
            old_name='food_type',
            new_name='drinking_habbit',
        ),
        migrations.RenameField(
            model_name='userfulldetails',
            old_name='smoke_habbit',
            new_name='smoking_habbit',
        ),
    ]
