# Generated by Django 2.2.5 on 2021-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0011_auto_20210321_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner_preferences',
            name='gotram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_preferences',
            name='sub_caste',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
