# Generated by Django 2.2.5 on 2021-04-04 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimony_app', '0014_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='FriendRequests',
        ),
    ]
