# Generated by Django 2.2.5 on 2021-04-04 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0015_auto_20210404_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequests',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendrequests',
            name='updated_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
