# Generated by Django 2.2.5 on 2021-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0016_auto_20210404_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequests',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
