# Generated by Django 2.2.5 on 2021-04-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0018_usermultifile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermultifile',
            name='basic_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony_app.UserFullDetails'),
        ),
    ]
