# Generated by Django 2.2.5 on 2021-04-11 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0019_auto_20210408_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField()),
                ('Ative_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='partner_preferences',
            name='Few_Words_MySelf',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
