# Generated by Django 2.2.5 on 2021-04-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0020_auto_20210411_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullDataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_user_id', models.CharField(max_length=100, null=True)),
                ('null_requested_user_id', models.CharField(max_length=100, null=True)),
                ('key_name', models.CharField(max_length=100, null=True)),
                ('key_data', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
